# =============================================================================
# run_mex_us.ps1 — SQL-CSI dump-overall 第一步 1.5.1
#
# Resolve cdb.exe (Windows Kits OR WinDbg Store/MSIX), write a headless-safe
# `-cf` batch that captures `!mex.us` (thread inventory) + basic metadata
# (`vertarget`, `lmvm sqlservr`) to a log, then run cdb.exe against the dump.
#
# Outputs (under -OutDir):
#   <case>_dump_commands.cdb    — the batch script
#   <case>_dump_output.txt      — cdb -logo capture (metadata + !mex.us)
#   <case>_us.txt               — .logopen inside cdb (feeds gen_us_html.ps1 / parse_us_states.ps1)
#
# EXIT CODES: 0 = success (both us.txt and dump_output.txt exist);
#             1 = cdb not found / run failed / log missing.
# =============================================================================
[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$Dump,
  [Parameter(Mandatory)][string]$MexPath,          # folder containing mex.dll
  [Parameter(Mandatory)][string]$OutDir,           # e.g. reports/<case>_dump_code_analysis
  [Parameter(Mandatory)][string]$CaseId,
  [string]$SymPath = 'srv*C:\Symbols*https://symweb.azurefd.net',
  [string]$Cdb     = $null,                        # optional explicit cdb path
  [int]$TimeoutSec = 300
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'resolve_cdb.ps1')

if (-not (Test-Path $Dump))    { throw "dump not found: $Dump" }
if (-not (Test-Path $MexPath)) { throw "mex_path not found: $MexPath" }
if (-not (Test-Path (Join-Path $MexPath 'mex.dll'))) { throw "mex.dll missing under: $MexPath" }
if (-not (Test-Path $OutDir))  { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

# ---- resolve cdb.exe ---------------------------------------------------------
$Cdb = Resolve-CdbPath -Cdb $Cdb
if (-not $Cdb) {
    Write-Host "[run_mex_us] ERROR: cdb.exe not found — install Windows Kits Debuggers or WinDbg Store package" -ForegroundColor Red
    exit 1
}
Write-Host "[run_mex_us] cdb.exe: $Cdb" -ForegroundColor Green

# ---- paths -------------------------------------------------------------------
$cdbBatch = Join-Path $OutDir "$($CaseId)_dump_commands.cdb"
$cdbLog   = Join-Path $OutDir "$($CaseId)_dump_output.txt"
$usLog    = Join-Path $OutDir "$($CaseId)_us.txt"

# ---- write cdb batch (UTF-8 no-BOM) -----------------------------------------
$batch = @"
* ============================================================================
* SQL-CSI dump-overall 第一步 · Case: $CaseId
* Generated by run_mex_us.ps1 — DO NOT edit by hand.
* ============================================================================
.sympath $SymPath
.reload /f
vertarget
lmvm sqlservr
.load $MexPath\mex.dll
.logopen $usLog
!mex.us
.logclose
q
"@
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($cdbBatch, $batch, $enc)
Write-Host "[run_mex_us] batch written: $cdbBatch"

# ---- run cdb -----------------------------------------------------------------
Write-Host "[run_mex_us] running cdb (timeout ${TimeoutSec}s)..."
$args = @('-y', $SymPath, '-z', $Dump, '-cf', $cdbBatch, '-logo', $cdbLog, '-G', '-lines')
$p = Start-Process -FilePath $Cdb -ArgumentList $args -PassThru -WindowStyle Hidden
if (-not $p.WaitForExit($TimeoutSec * 1000)) {
    try { $p.Kill() } catch {}
    Write-Host "[run_mex_us] ERROR: cdb timed out after $TimeoutSec s" -ForegroundColor Red
    exit 1
}

# ---- verify outputs ----------------------------------------------------------
$okOut = Test-Path $cdbLog
$okUs  = Test-Path $usLog
$szUs  = if ($okUs) { (Get-Item $usLog).Length } else { 0 }
Write-Host ("[run_mex_us] result: dump_output.txt={0}  us.txt={1} ({2} bytes)" -f $okOut, $okUs, $szUs) `
    -ForegroundColor (($okOut -and $okUs -and $szUs -gt 0) ? 'Green' : 'Red')
if ($okOut -and $okUs -and $szUs -gt 0) { exit 0 } else { exit 1 }
