# =============================================================================
# run_windbgcs_tasks.ps1 — SQL-CSI dump-overall 第一步 1.5.5
#
# Headless cdb.exe driver for the WinDbgCs "Tasks.Enumerate" mirror. Uses the
# `!dcs_initsymsvr` entry point (works on SQL 2019 / 2022 / 2025) — this is the
# same sequence a human runs in the WinDbg GUI, just piped via cdb `-cf`.
#
# Bypasses in-process Roslyn CodeGen (which fails on many SQL 2022/2025 dumps).
#
# Outputs (under -OutDir):
#   <case>_tasks_commands.cdb   — the batch script
#   <case>_tasks_output.txt     — cdb -logo capture (metadata + Tasks.Enumerate)
#
# Prefer this over run_sqlscriptrepl.ps1 for SQL 2022 / 2025 dumps. Use
# run_sqlscriptrepl.ps1 as a fallback on SQL 2019 dumps where WinDbgCsExt v3.2.7
# + local NetStandard20Refs bundle is preferred.
#
# EXIT CODES: 0 = success (output contains "TaskOutput:" marker);
#             1 = cdb not found / timeout / marker missing.
# =============================================================================
[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$Dump,
  [Parameter(Mandatory)][string]$OutDir,           # e.g. reports/<case>_dump_code_analysis
  [Parameter(Mandatory)][string]$CaseId,
  [string]$Wdbgcs   = 'C:\Tools\WinDbgCs',         # folder containing WinDbgCsExt.dll
  [string]$SymPath  = 'srv*C:\Symbols*https://symweb.azurefd.net',
  [string]$Cdb      = $null,                        # optional explicit cdb path
  [int]$TimeoutSec  = 600
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'resolve_cdb.ps1')

if (-not (Test-Path $Dump))    { throw "dump not found: $Dump" }
if (-not (Test-Path $Wdbgcs))  { throw "wdbgcs folder not found: $Wdbgcs" }
$ext = Join-Path $Wdbgcs 'WinDbgCsExt.dll'
if (-not (Test-Path $ext))     { throw "WinDbgCsExt.dll missing under: $Wdbgcs" }
if (-not (Test-Path $OutDir))  { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

# ---- resolve cdb.exe ---------------------------------------------------------
$Cdb = Resolve-CdbPath -Cdb $Cdb
if (-not $Cdb) {
    Write-Host "[run_windbgcs_tasks] ERROR: cdb.exe not found — install Windows Kits Debuggers or WinDbg Store package (any of Microsoft.WinDbg / .Fast / .Slow / .Preview)" -ForegroundColor Red
    exit 1
}
Write-Host "[run_windbgcs_tasks] cdb.exe   : $Cdb"       -ForegroundColor Green
Write-Host "[run_windbgcs_tasks] WinDbgCs  : $Wdbgcs"    -ForegroundColor Green
Write-Host "[run_windbgcs_tasks] dump      : $Dump"      -ForegroundColor Green

# ---- paths -------------------------------------------------------------------
$cdbBatch  = Join-Path $OutDir "$($CaseId)_tasks_commands.cdb"
$cdbLog    = Join-Path $OutDir "$($CaseId)_tasks_output.txt"

# ---- write cdb batch (UTF-8 no-BOM) -----------------------------------------
# This is the same sequence a human runs manually in WinDbg GUI — see SKILL.md
# Path B (b) block. `.reload /f sbs.dll` failing is HARMLESS. A handful of
# `InvalidMemoryAddressException` rows on a filtered minidump are BENIGN.
$batch = @"
* ============================================================================
* SQL-CSI dump-overall 1.5.5 · Case: $CaseId
* Generated by run_windbgcs_tasks.ps1 — DO NOT edit by hand.
* Uses !dcs_initsymsvr (bypasses in-process Roslyn CodeGen).
* ============================================================================
.sympath $SymPath
.reload /f
vertarget
lmvm sqlservr
.load $ext
!dcs_initsymsvr ;
.reload /f sqlos.dll ;
.reload /f sqldk.dll ;
.reload /f sqlmin.dll ;
.reload /f sqllang.dll ;
.reload /f qds.dll ;
.reload /f sqlTsEs.dll ;
.reload /f svl.dll ;
.reload /f sbs.dll ;
.reload /f sqlvdi.dll ;
.reload /f sqlservr.exe ;
.reload /f hkengine.dll ;
.reload /f hkruntime.dll ;
.reload /f hkcompile.dll ;
.reload /f kernel32.dll ;
.reload /f ntdll.dll ;
.reload /f kernelbase.dll ;
!execute ;
!execute ExternalScripts.Install ;
.ecxr ;
kc ;
!execute Tasks.Enumerate
q
"@
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($cdbBatch, $batch, $enc)
Write-Host "[run_windbgcs_tasks] batch written: $cdbBatch"

# ---- run cdb -----------------------------------------------------------------
Write-Host "[run_windbgcs_tasks] running cdb (timeout ${TimeoutSec}s)..."
$args = @('-y', $SymPath, '-z', $Dump, '-cf', $cdbBatch, '-logo', $cdbLog, '-G', '-lines')
$p = Start-Process -FilePath $Cdb -ArgumentList $args -PassThru -WindowStyle Hidden
if (-not $p.WaitForExit($TimeoutSec * 1000)) {
    try { $p.Kill() } catch {}
    Write-Host "[run_windbgcs_tasks] ERROR: cdb timed out after $TimeoutSec s" -ForegroundColor Red
    exit 1
}

# ---- verify outputs ----------------------------------------------------------
if (-not (Test-Path $cdbLog)) {
    Write-Host "[run_windbgcs_tasks] ERROR: log not written: $cdbLog" -ForegroundColor Red
    exit 1
}
$sz     = (Get-Item $cdbLog).Length
$hasMk  = (Select-String -Path $cdbLog -Pattern 'TaskOutput:' -SimpleMatch -Quiet)
$hasRun = (Select-String -Path $cdbLog -Pattern 'Running:Tasks' -SimpleMatch -Quiet)
$hasHeader = (Select-String -Path $cdbLog -Pattern '^task\s+\|\s+scheduler_id\s+\|\s+worker\s+\|\s+thread\s+\|\s+task_state\s+\|' -Quiet)
$hasRows = (Select-String -Path $cdbLog -Pattern '^0x[0-9a-fA-F`]+\s+\|\s+\d+\s+\|' -Quiet)
$validTasks = $hasMk -or ($hasRun -and $hasHeader -and $hasRows)
Write-Host ("[run_windbgcs_tasks] result: tasks_output.txt = {0} bytes; TaskOutput marker = {1}; valid Tasks pipe table = {2}" -f $sz, $hasMk, ($hasRun -and $hasHeader -and $hasRows)) `
    -ForegroundColor ($(if ($validTasks) { 'Green' } else { 'Red' }))
if ($validTasks) { exit 0 } else {
    Write-Host "[run_windbgcs_tasks] NOTE: If !dcs_initsymsvr 404'd or CodeGen failed, fall back to run_sqlscriptrepl.ps1 with a pre-seeded NetStandard20Refs\<build> bundle." -ForegroundColor Yellow
    exit 1
}
